Clean up, drop fix_mo

diff --git a/check_elf_files b/check_elf_files
--- a/check_elf_files
+++ b/check_elf_files
@@ -2,20 +2,18 @@
 # Check elf files
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "No build root defined" >&2
-    exit 1
+	echo "No build root defined" >&2
+	exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "Invalid build root" >&2
-    exit 1
+	echo "Invalid build root" >&2
+	exit 1
 fi
 
 LIB="$(rpm --eval %{_lib})"
 export LD_LIBRARY_PATH="$RPM_BUILD_ROOT/$LIB:$RPM_BUILD_ROOT/usr/$LIB"
 
-
-# TODO: would be nicer to search through files only once..
 find "$RPM_BUILD_ROOT" -type f \( -executable -o -name \*.so\* \) -a \
 	\( ! -path $RPM_BUILD_ROOT/usr/lib/debug/\* -a \
 	   ! -path $RPM_BUILD_ROOT/usr/src/debug/\* \) \
@@ -23,29 +21,17 @@ find "$RPM_BUILD_ROOT" -type f \( -executable -o -name \*.so\* \) -a \
 xargs  --no-run-if-empty -0 file -N -L |
 grep -e '\.so.*: ELF.*shared' -e ': ELF.*executable' |
 while read match; do
-path="$(echo $match | cut -d':' -f1)"
-syspath="$(echo $path | sed -e "s#^$RPM_BUILD_ROOT##")"
-if printf '%s\n' $match | grep -q -e ': ELF'; then
-    unused_libs="$(ldd -u -r $path 2> /dev/null | grep /)"
-    if [ -n "$unused_libs" ]; then
-	printf '%s\n' "Warning: unused libraries in $syspath: " >&2
-	printf '%s\n' "$unused_libs" >&2
-    fi
-fi
-done
-
-find "$RPM_BUILD_ROOT" -type f -name \*.so\*  -a \
-	\( ! -path $RPM_BUILD_ROOT/usr/lib/debug/\* -a \
-	   ! -path $RPM_BUILD_ROOT/usr/src/debug/\* \) \
-	-print0 |
-xargs  --no-run-if-empty -0 file -N -L |
-grep -e '\.so.*: ELF.*shared' |
-while read match; do
-path="$(echo $match | cut -d':' -f1)"
-syspath="$(echo $path | sed -e "s#^$RPM_BUILD_ROOT##")"
-unused_libs="$(ldd -u -r $path 2> /dev/null | grep /)"
-undefined_symbols="$(ldd -r $path 2>&1 | grep '^undefined symbol: '| sed -e 's#^undefined symbol:##g' -e "s#($path).*##g" | tr -d '\n' | tr -d '\t')"
-if [ -n "$undefined_symbols" ]; then
-    printf '%s\n' "Warning: undefined symbols in $syspath:$undefined_symbols" >&2
-fi
+	path="$(echo $match | cut -d':' -f1)"
+	syspath="$(echo $path | sed -e "s#^$RPM_BUILD_ROOT##")"
+	unused_libs="$(ldd -u -r $path 2> /dev/null | grep /)"
+	if [ -n "$unused_libs" ]; then
+		printf '%s\n' "Warning: unused libraries in $syspath: " >&2
+		printf '%s\n' "$unused_libs" >&2
+	fi
+	if echo $match |grep -q shared; then
+		undefined_symbols="$(ldd -r $path 2>&1 | grep '^undefined symbol: '| sed -e 's#^undefined symbol:##g' -e "s#($path).*##g" | tr -d '\n' | tr -d '\t')"
+		if [ -n "$undefined_symbols" ]; then
+			printf '%s\n' "Warning: undefined symbols in $syspath:$undefined_symbols" >&2
+		fi
+	fi
 done
diff --git a/clean_files b/clean_files
--- a/clean_files
+++ b/clean_files
@@ -2,20 +2,20 @@
 # remove backup files
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "No build root defined" >&2
-    exit 1
+	printf '%s\n' "No build root defined" >&2
+	exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "Invalid build root" >&2
-    exit 1
+	printf '%s\n' "Invalid build root" >&2
+	exit 1
 fi
 
 if [ -n "$1" ]; then
-    DIRECTORY=$(printf '%s\n' $1 | sed -e "s#^$RPM_BUILD_ROOT##g")
-    if [ ! -d "$RPM_BUILD_ROOT$DIRECTORY" ]; then
-	exit 0
-    fi
+	DIRECTORY=$(printf '%s\n' $1 | sed -e "s#^$RPM_BUILD_ROOT##g")
+	if [ ! -d "$RPM_BUILD_ROOT$DIRECTORY" ]; then
+		exit 0
+	fi
 fi
 
 find "$RPM_BUILD_ROOT$DIRECTORY" \( -type f -o -type l \) \( \
@@ -35,4 +35,4 @@ find "$RPM_BUILD_ROOT$DIRECTORY" \( -type f -o -type l \) \( \
 	-name core \) \
 	-delete
 
-find "$RPM_BUILD_ROOT$DIRECTORY" -type d -name CVS | xargs rm -rf
+find "$RPM_BUILD_ROOT$DIRECTORY" -type d -name CVS -o -name .git -o -name .svn | xargs rm -rf
diff --git a/fix_eol b/fix_eol
--- a/fix_eol
+++ b/fix_eol
@@ -2,27 +2,27 @@
 # convert end of line patterns from DOS to UNIX
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "No build root defined" >&2
-    exit 1
+	printf '%s\n' "No build root defined" >&2
+	exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "Invalid build root" >&2
-    exit 1
+	printf '%s\n' "Invalid build root" >&2
+	exit 1
 fi
 
 if [ -n "$1" ]; then
-    DIRECTORY=$(printf '%s\n' $1 | sed -e "s#^$RPM_BUILD_ROOT##g")
-    if [ ! -d "$RPM_BUILD_ROOT$DIRECTORY" ]; then
-	exit 0
-    fi
+	DIRECTORY=$(printf '%s\n' $1 | sed -e "s#^$RPM_BUILD_ROOT##g")
+	if [ ! -d "$RPM_BUILD_ROOT$DIRECTORY" ]; then
+		exit 0
+	fi
 fi
 
 find "$RPM_BUILD_ROOT$DIRECTORY" -type f | while read f; do
-    if [ -n "$EXCLUDE_FROM_EOL_CONVERSION" ]; then
-	basename "$f" | grep -q -P "$EXCLUDE_FROM_EOL_CONVERSION" && continue
-    fi
-    grep -q -Ilsr $'\r$' "$f" && sed -e 's/\r$//' -i "$f"
+	if [ -n "$EXCLUDE_FROM_EOL_CONVERSION" ]; then
+		basename "$f" | grep -q -P "$EXCLUDE_FROM_EOL_CONVERSION" && continue
+	fi
+	grep -q -Ilsr $'\r$' "$f" && sed -e 's/\r$//' -i "$f"
 done
 
 exit 0
diff --git a/fix_file_permissions b/fix_file_permissions
--- a/fix_file_permissions
+++ b/fix_file_permissions
@@ -1,38 +1,38 @@
 #!/bin/sh
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "No build root defined" >&2
-    exit 1
+	printf '%s\n' "No build root defined" >&2
+	exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "Invalid build root" >&2
-    exit 1
+	printf '%s\n' "Invalid build root" >&2
+	exit 1
 fi
 
 find "$RPM_BUILD_ROOT" \
-    ! -path "${RPM_BUILD_ROOT}/usr/lib/debug/*" \
-    ! -path "${RPM_BUILD_ROOT}/usr/doc/*" \
-    ! -path "${RPM_BUILD_ROOT}/usr/share/doc/*" \
-    -type f \( -name \*.exe -o -name \*.dll -o -name \*.so\* \) -print0 |
+	! -path "${RPM_BUILD_ROOT}/usr/lib/debug/*" \
+	! -path "${RPM_BUILD_ROOT}/usr/doc/*" \
+	! -path "${RPM_BUILD_ROOT}/usr/share/doc/*" \
+	-type f \( -name \*.exe -o -name \*.dll -o -name \*.so\* \) -print0 |
 xargs  --no-run-if-empty -0 file -N -F ' //magic:' |
 grep -e "Mono/.Net assembly" -e "ELF.*shared object" |
 sed -e 's# //magic:.*##g' |
 while read path; do
-    PERMS=$(stat -c '%a' "$path")
-    if [ $PERMS -lt 755 ]; then
-	chmod 755 "$path"
-    fi
+	PERMS=$(stat -c '%a' "$path")
+	if [ $PERMS -lt 755 ]; then
+		chmod 755 "$path"
+	fi
 done
 
 if [ -d "${RPM_BUILD_ROOT}/usr/share/info/" ]; then
-    find "${RPM_BUILD_ROOT}/usr/share/info/" \
+	find "${RPM_BUILD_ROOT}/usr/share/info/" \
 	-type f -print0 |
-    xargs --no-run-if-empty -0 chmod 644
+	xargs --no-run-if-empty -0 chmod 644
 fi
 
 if [ -d "${RPM_BUILD_ROOT}/usr/share/man/" ]; then
-    find "${RPM_BUILD_ROOT}/usr/share/man/" \
+	find "${RPM_BUILD_ROOT}/usr/share/man/" \
 	-type f -print0 |
-    xargs --no-run-if-empty -0 chmod 644
+	xargs --no-run-if-empty -0 chmod 644
 fi
diff --git a/fix_pkgconfig b/fix_pkgconfig
--- a/fix_pkgconfig
+++ b/fix_pkgconfig
@@ -7,13 +7,13 @@
 # (c) Andrey Bondrov <andrey.bondrov@rosalab.ru> 2016
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "No build root defined" >&2
-    exit 1
+	printf '%s\n' "No build root defined" >&2
+	exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "Invalid build root" >&2
-    exit 1
+	printf '%s\n' "Invalid build root" >&2
+	exit 1
 fi
 
 for pc in $(find "$RPM_BUILD_ROOT" -name \*.pc -type f); do
diff --git a/lib_symlinks b/lib_symlinks
--- a/lib_symlinks
+++ b/lib_symlinks
@@ -1,11 +1,11 @@
 #!/bin/sh
 #---------------------------------------------------------------
-# Project         : Linux-Mandrake
-# Module          : spec-helper
-# File            : lib_symlinks
-# Author          : Frederic Lepied
-# Created On      : Tue Nov  7 08:33:05 2000
-# Description     : Run ldconfig to create symlinks to libraries.
+# Project	: Linux-Mandrake
+# Module	: spec-helper
+# File		: lib_symlinks
+# Author	: Frederic Lepied
+# Created On	: Tue Nov  7 08:33:05 2000
+# Description	: Run ldconfig to create symlinks to libraries.
 #
 # Copyright (C) 2000 by Frederic Lepied <flepied@mandrakesoft.com>
 # Redistribution of this file is permitted under the terms of the GNU 
@@ -13,13 +13,13 @@
 #---------------------------------------------------------------
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "No build root defined" >&2
-    exit 1
+	printf '%s\n' "No build root defined" >&2
+	exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "Invalid build root" >&2
-    exit 1
+	printf '%s\n' "Invalid build root" >&2
+	exit 1
 fi
 
 libs=$(find "$RPM_BUILD_ROOT" -type d \
@@ -27,7 +27,7 @@ libs=$(find "$RPM_BUILD_ROOT" -type d \
    -a ! "(" -path '*/usr/src/debug*' -o -path '*/usr/lib/debug*' ")")
 
 if [ -n "$libs" ] || [ -n "$EXTRA_LIBS_TO_SYMLINK" ]; then
-    /sbin/ldconfig -n -N $libs $EXTRA_LIBS_TO_SYMLINK
+	/sbin/ldconfig -n -N $libs $EXTRA_LIBS_TO_SYMLINK
 fi
 
 # lib_symlinks ends here
diff --git a/python_shebangs b/python_shebangs
--- a/python_shebangs
+++ b/python_shebangs
@@ -1,13 +1,20 @@
 #!/bin/sh
+# This is not run by default because - regardless of what
+# certain other distributions may think - an unversioned
+# python shebang being defined as "give me the latest
+# and greatest python available" is very much allowed.
+#
+# It is provided because it makes sense to have versioned
+# shebangs on projects not compatible with a new version.
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "No build root defined" >&2
-    exit 1
+	printf '%s\n' "No build root defined" >&2
+	exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "Invalid build root" >&2
-    exit 1
+	printf '%s\n' "Invalid build root" >&2
+	exit 1
 fi
 
 set -efu
@@ -17,28 +24,26 @@ tmpfile="$(mktemp)"
 trap 'rm -f "$tmpfile"' EXIT
 printf '%s\n' "0" > "$tmpfile"
 
-for dir in /bin /usr/bin /sbin /usr/sbin /usr/libexec
-do
-    if [ ! -d "${RPM_BUILD_ROOT}/${dir}" ]; then
-	continue
-    fi
-    find "${RPM_BUILD_ROOT}/${dir}" -type f -print | \
-    while read -r file
-    do
-    # Prohibit shebangs like:
-    # #!/usr/bin/python
-    # #! /usr/bin/python
-    # #!/usr/bin/env python
-    # #! /usr/bin/env python
-    # Note that a space may be in the end of the shebang line
-	if head -n 1 "$file" | grep -qE '^#!([[:blank:]])*.*(/python|[[:blank:]]python)([[:blank:]])*$' ; then
-	    printf '%s\n' "Unversioned Python shebangs are not allowed. Specify python3 or python2 explicitly in $file"
-	    # Do not fail on the 1st error, print all errors at one time
-	    printf '%s\n' "1" > "$tmpfile"
+for dir in /bin /usr/bin /sbin /usr/sbin /usr/libexec; do
+	if [ ! -d "${RPM_BUILD_ROOT}/${dir}" ]; then
+		continue
 	fi
-    done
+	find "${RPM_BUILD_ROOT}/${dir}" -type f -print | \
+	while read -r file; do
+		# Prohibit shebangs like:
+		# #!/usr/bin/python
+		# #! /usr/bin/python
+		# #!/usr/bin/env python
+		# #! /usr/bin/env python
+		# Note that a space may be in the end of the shebang line
+		if head -n 1 "$file" | grep -qE '^#!([[:blank:]])*.*(/python|[[:blank:]]python)([[:blank:]])*$' ; then
+			printf '%s\n' "Unversioned Python shebangs are not allowed. Specify python3 or python2 explicitly in $file"
+			# Do not fail on the 1st error, print all errors at one time
+			printf '%s\n' "1" > "$tmpfile"
+		fi
+	done
 done
 
 if [ "$(head -n 1 "$tmpfile")" != 0 ]; then
-    exit 1
+	exit 1
 fi
diff --git a/rediff_patch b/rediff_patch
--- a/rediff_patch
+++ b/rediff_patch
@@ -16,70 +16,63 @@
 shopt -s nullglob
 
 spec_count=`ls -1 *spec 2>/dev/null | wc -l`
-if [[ $spec_count != 1 ]] 
-then 
-    echo "Can't detect spec file to work with - current folder either contains no spec files or contains several spec files."
-    exit
+if [[ $spec_count != 1 ]]; then 
+	echo "Can't detect spec file to work with - current folder either contains no spec files or contains several spec files."
+	exit
 fi
 
 target_patch=$1
 tarball=$2
 
-if [[ $target_patch == '-h' || $target_patch == '--help' ]]
-then
-    echo "USAGE: $0 [patch_to_rediff] [source_tarball] "
-    echo "         * if patch is not specified and the current folder contains only one patch,"
-    echo "         then that patch will be rediffed"
-    echo "         * if tarball is not specified and the current folder contains only one tarball,"
-    echo "         then the patch will be applied to content of that tarball"
-    echo "         * all actions are performed in rediff_patch subfolder of the current folder"
-    echo "         if rediff fails, that subfolder will not be removed and you will be able to "
-    echo "         finalize rediff manually"
+if [[ $target_patch == '-h' || $target_patch == '--help' ]]; then
+	echo "USAGE: $0 [patch_to_rediff] [source_tarball] "
+	echo "		 * if patch is not specified and the current folder contains only one patch,"
+	echo "		 then that patch will be rediffed"
+	echo "		 * if tarball is not specified and the current folder contains only one tarball,"
+	echo "		 then the patch will be applied to content of that tarball"
+	echo "		 * all actions are performed in rediff_patch subfolder of the current folder"
+	echo "		 if rediff fails, that subfolder will not be removed and you will be able to "
+	echo "		 finalize rediff manually"
 
-    exit 1
+	exit 1
 fi
 
 # Remember number of patch files in current dir
 patch_count=`ls -1 *patch 2>/dev/null | wc -l`
 
-if [[ "${target_patch}" == "" ]]
-then
-    # if no patch is provided as script argument and there is only a single patch in the folder,
-    # let's proceed with that patch. Otherwise, exit
-    if [[ $patch_count != 1 ]]
-    then 
-        if [[ $patch_count == 0 ]]
-        then
-            echo "No patch specified as an argument and current directory contains no patches"
-        else
-            echo "No patch specified as an argument and current directory contains more than one patch file"
-        fi
-        exit 1
-    else
-        target_patch=`ls -1 *patch`
-        echo "No patch specified as an argument, processing ${target_patch}"
-    fi
+if [[ "${target_patch}" == "" ]]; then
+	# if no patch is provided as script argument and there is only a single patch in the folder,
+	# let's proceed with that patch. Otherwise, exit
+	if [[ $patch_count != 1 ]]; then 
+		if [[ $patch_count == 0 ]]; then
+			echo "No patch specified as an argument and current directory contains no patches"
+		else
+			echo "No patch specified as an argument and current directory contains more than one patch file"
+		fi
+		exit 1
+	else
+		target_patch=`ls -1 *patch`
+		echo "No patch specified as an argument, processing ${target_patch}"
+	fi
 fi
 
 # Detect how the patch should be applied
 grep -q '%apply_patches' *.spec
-if [[ $? == 0 ]]
-then
-    # %apply_patches is used
-    patch_cmd="patch -p1 --force"
-elif [[ $patch_count == 1 ]]
-then
-    # only one patch and no %apply_patches, so we can expect the only %patch command in the spec
-    patch_cmd=`grep '^%patch' *spec | cut -f1,2 -d- | sed 's/^%patch[[:digit:]]*/patch --force /'`
+if [[ $? == 0 ]]; then
+	# %apply_patches is used
+	patch_cmd="patch -p1 --force"
+elif [[ $patch_count == 1 ]]; then
+	# only one patch and no %apply_patches, so we can expect the only %patch command in the spec
+	patch_cmd=`grep '^%patch' *spec | cut -f1,2 -d- | sed 's/^%patch[[:digit:]]*/patch --force /'`
 else
-    # grep for Patch: record in spec corresponding to our patch
-    # drop name from the beginning of the patch name,
-    # since one can use %name or %{name} in patch name in spec
-    project=`basename "$PWD"`
-    patch_num=`grep "^Patch.*${target_patch/$project/}" *spec | sed 's/^Patch\([[:digit:]]*\).*$/\1/'`
+	# grep for Patch: record in spec corresponding to our patch
+	# drop name from the beginning of the patch name,
+	# since one can use %name or %{name} in patch name in spec
+	project=`basename "$PWD"`
+	patch_num=`grep "^Patch.*${target_patch/$project/}" *spec | sed 's/^Patch\([[:digit:]]*\).*$/\1/'`
 
-    # now grep for necessary %patch command
-    patch_cmd=`grep "\%patch${patch_num}[[:space:]]\|\%patch${patch_num}\$" *spec | cut -f1,2 -d- | sed 's/^\%patch[[:digit:]]*/patch --force /'`
+	# now grep for necessary %patch command
+	patch_cmd=`grep "\%patch${patch_num}[[:space:]]\|\%patch${patch_num}\$" *spec | cut -f1,2 -d- | sed 's/^\%patch[[:digit:]]*/patch --force /'`
 fi
 
 rm -rf rediff_patch
@@ -88,80 +81,62 @@ pushd rediff_patch
 
 # if we have relative path, add "../" to it
 echo $tarball | grep -q "^/"
-if [[ $? != 0 ]]
-then
-    tarball="../$tarball"
+if [[ $? != 0 ]]; then
+	tarball="../$tarball"
 fi
 
 # tarball is specified in cmd line, let's unpack it
-if [[ $tarball =~ ".tar.gz" ]] 
-then 
-    tar xzf $tarball
-elif [[ $tarball =~ ".tgz" ]] 
-then 
-    tar xzf $tarball
-elif [[ $tarball =~ ".tar.Z" ]] 
-then 
-    tar xZf $tarball
-elif [[ $tarball =~ ".tar.bz2" ]] 
-then
-    tar xjf $tarball
-elif [[ $tarball =~ ".tbz2" ]] 
-then
-    tar xjf $tarball
-elif [[ $tarball =~ ".tar.xz" ]] 
-then 
-    tar xJf $tarball
-elif [[ $tarball =~ ".zip" ]] 
-then 
-    unzip $tarball
-elif [[ ! $tarball =~ "" ]]
-then
-    echo "Tarball type is not recognized, failed to unpack"
-    popd
-    rm -rf rediff_patch
-    exit 1
+if [[ $tarball =~ ".tar.gz" ]]; then 
+	tar xzf $tarball
+elif [[ $tarball =~ ".tgz" ]]; then 
+	tar xzf $tarball
+elif [[ $tarball =~ ".tar.Z" ]]; then 
+	tar xZf $tarball
+elif [[ $tarball =~ ".tar.bz2" ]]; then
+	tar xjf $tarball
+elif [[ $tarball =~ ".tbz2" ]]; then
+	tar xjf $tarball
+elif [[ $tarball =~ ".tar.xz" ]]; then 
+	tar xJf $tarball
+elif [[ $tarball =~ ".zip" ]]; then 
+	unzip $tarball
+elif [[ ! $tarball =~ "" ]]; then
+	echo "Tarball type is not recognized, failed to unpack"
+	popd
+	rm -rf rediff_patch
+	exit 1
 fi
 
 # Tarball is not specified - let's detect it
 # We only support the situaiton with single tarball in the folder
-if [[ -n $(echo ../*.tar.gz) ]] 
-then 
-    tar xzf ../*tar.gz
-elif [[ -n $(echo ../*.tgz) ]] 
-then 
-    tar xzf ../*tgz
-elif [[ -n $(echo ../*.tar.Z) ]] 
-then 
-    tar xZf ../*tar.Z
-elif [[ -n $(echo ../*.tar.bz2) ]] 
-then
-    tar xjf ../*tar.bz2
-elif [[ -n $(echo ../*.tbz2) ]] 
-then
-    tar xjf ../*tbz2
-elif [[ -n $(echo ../*.tar.xz) ]] 
-then 
-    tar xJf ../*tar.xz
-elif [[ -n $(echo ../*.zip) ]] 
-then 
-    unzip ../*zip
+if [[ -n $(echo ../*.tar.gz) ]]; then 
+	tar xzf ../*tar.gz
+elif [[ -n $(echo ../*.tgz) ]]; then 
+	tar xzf ../*tgz
+elif [[ -n $(echo ../*.tar.Z) ]]; then 
+	tar xZf ../*tar.Z
+elif [[ -n $(echo ../*.tar.bz2) ]]; then
+	tar xjf ../*tar.bz2
+elif [[ -n $(echo ../*.tbz2) ]]; then
+	tar xjf ../*tbz2
+elif [[ -n $(echo ../*.tar.xz) ]]; then 
+	tar xJf ../*tar.xz
+elif [[ -n $(echo ../*.zip) ]]; then 
+	unzip ../*zip
 fi
 
 # Let's check how many folders exist in the current one after tarball unpacking
 # We support only the situation when we have a single folder (except .git)
 # which will be subjected to patching then
 count=`ls -l | grep -v .git | grep '^d' 2>/dev/null | wc -l`
-if [[ $count != 1 ]]
-then 
-    if [[ $count == 0 ]]
-    then
-        echo "No folders, something went wrong with unpacking of tarball"
-    else
-        echo "More than one folder found - it seems that we have a tarball bomb, this is not curently supported"
-    fi
-    popd
-    exit 1
+if [[ $count != 1 ]]; then 
+	if [[ $count == 0 ]]; then
+		echo "No folders, something went wrong with unpacking of tarball"
+	else
+		echo "More than one folder found - it seems that we have a tarball bomb, this is not curently supported"
+	fi
+	popd
+	exit 1
 fi
 
 # Create folder backup and try to apply the patch
@@ -174,39 +149,35 @@ cd $folder
 failed=0
 echo "$patch_cmd < $target_patch"
 $patch_cmd < $target_patch
-if [[ $? != 0 ]]
-then
-    failed=1
-    echo "Rediff failed, you should rework the patch"
+if [[ $? != 0 ]]; then
+	failed=1
+	echo "Rediff failed, you should rework the patch"
 fi
 
 cd ..
 
 
-if [[ $failed == 0 ]]
-then
-    # Patch succeeded, let's recreate it
-    rm -f $folder/$target_patch
-    find $folder -name "*.orig" -delete
-    diff -Naur ${folder}.orig $folder > ../${target_patch}.new
+if [[ $failed == 0 ]]; then
+	# Patch succeeded, let's recreate it
+	rm -f $folder/$target_patch
+	find $folder -name "*.orig" -delete
+	diff -Naur ${folder}.orig $folder > ../${target_patch}.new
 
-    # .. and replace patch command in spec
-    # in case of %apply_patches, nothing to do
-    grep -q '%apply_patches' ../*.spec
-    if [[ $? != 0 ]]
-    then
-        if [[ $patch_count == 1 ]]
-        then
-            sed -i 's/^\%patch\(.*\) -p[[:digit:]]*/\%patch\1 -p1/' ../*spec
-        else
-            sed -i "s/^\%patch${patch_num} -p[[:digit:]]*/\%patch${patch_num} -p1/" ../*spec
-        fi
-    fi
+	# .. and replace patch command in spec
+	# in case of %apply_patches, nothing to do
+	grep -q '%apply_patches' ../*.spec
+	if [[ $? != 0 ]]; then
+		if [[ $patch_count == 1 ]]; then
+			sed -i 's/^\%patch\(.*\) -p[[:digit:]]*/\%patch\1 -p1/' ../*spec
+		else
+			sed -i "s/^\%patch${patch_num} -p[[:digit:]]*/\%patch${patch_num} -p1/" ../*spec
+		fi
+	fi
 
-    rm -rf ${folder}.orig $folder
+	rm -rf ${folder}.orig $folder
 else
-    popd # out from rediff_patch folder
-    exit 1
+	popd # out from rediff_patch folder
+	exit 1
 fi
 
 popd # out from rediff_patch folder
diff --git a/remove_info_dir b/remove_info_dir
--- a/remove_info_dir
+++ b/remove_info_dir
@@ -1,13 +1,13 @@
 #!/bin/sh
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "No build root defined" >&2
-    exit 1
+	printf '%s\n' "No build root defined" >&2
+	exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "Invalid build root" >&2
-    exit 1
+	printf '%s\n' "Invalid build root" >&2
+	exit 1
 fi
 
 INFODIR=$(rpm --eval %{_infodir}/dir)
@@ -15,5 +15,5 @@ INFODIR=$(rpm --eval %{_infodir}/dir)
 dir="$RPM_BUILD_ROOT/$INFODIR"
 
 if [ -f $dir ] && [ ! -f "$RPM_BUILD_ROOT/sbin/install-info" ] && [ ! -f "$RPM_BUILD_ROOT/usr/sbin/install-info" ]; then
-    rm -f $dir
+	rm -f $dir
 fi
diff --git a/remove_libtool_files b/remove_libtool_files
--- a/remove_libtool_files
+++ b/remove_libtool_files
@@ -1,13 +1,13 @@
 #!/bin/sh
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "No build root defined" >&2
-    exit 1
+	printf '%s\n' "No build root defined" >&2
+	exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "Invalid build root" >&2
-    exit 1
+	printf '%s\n' "Invalid build root" >&2
+	exit 1
 fi
 
 find "$RPM_BUILD_ROOT" \( -type f -o -type l \) -name \*.la  -print0 |
@@ -15,5 +15,5 @@ xargs  --no-run-if-empty -0 file -N -L |
 grep "libtool library file" |
 sed -e 's#: libtool library file.*##g' |
 while read path; do
-    rm -f "$path"
+	rm -f "$path"
 done
diff --git a/remove_rpath b/remove_rpath
--- a/remove_rpath
+++ b/remove_rpath
@@ -1,37 +1,37 @@
 #!/bin/sh
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "No build root defined" >&2
-    exit 1
+	printf '%s\n' "No build root defined" >&2
+	exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    printf '%s\n' "Invalid build root" >&2
-    exit 1
+	printf '%s\n' "Invalid build root" >&2
+	exit 1
 fi
 
 find "$RPM_BUILD_ROOT" \
-    ! -path "${RPM_BUILD_ROOT}/usr/lib/debug/*" \
-    ! -path "${RPM_BUILD_ROOT}/usr/doc/*" \
-    ! -path "${RPM_BUILD_ROOT}/usr/share/doc/*" \
-    ! -path "${RPM_BUILD_ROOT}/usr/share/man/*" \
-    ! -path "${RPM_BUILD_ROOT}/usr/share/mime/*" \
-    ! -path "${RPM_BUILD_ROOT}/usr/share/icons/*" \
-    ! -path "${RPM_BUILD_ROOT}/usr/share/pixmaps/*" \
-    ! -path "${RPM_BUILD_ROOT}/usr/share/zoneinfo/*" \
-    ! -path "${RPM_BUILD_ROOT}/usr/share/locale/*" \
-    ! -path "${RPM_BUILD_ROOT}/usr/src/*" \
-    ! -path "${RPM_BUILD_ROOT}/usr/include/*" \
-    -type f  -print0 |
+	! -path "${RPM_BUILD_ROOT}/usr/lib/debug/*" \
+	! -path "${RPM_BUILD_ROOT}/usr/doc/*" \
+	! -path "${RPM_BUILD_ROOT}/usr/share/doc/*" \
+	! -path "${RPM_BUILD_ROOT}/usr/share/man/*" \
+	! -path "${RPM_BUILD_ROOT}/usr/share/mime/*" \
+	! -path "${RPM_BUILD_ROOT}/usr/share/icons/*" \
+	! -path "${RPM_BUILD_ROOT}/usr/share/pixmaps/*" \
+	! -path "${RPM_BUILD_ROOT}/usr/share/zoneinfo/*" \
+	! -path "${RPM_BUILD_ROOT}/usr/share/locale/*" \
+	! -path "${RPM_BUILD_ROOT}/usr/src/*" \
+	! -path "${RPM_BUILD_ROOT}/usr/include/*" \
+	-type f  -print0 |
 xargs  --no-run-if-empty -0 file -N -F ' //magic:' |
 grep -e "ELF" |
 sed -e 's# //magic:.*##g' |
 while read path; do
-    RPATH=$(chrpath -l "$path" 2>/dev/null| grep -e RUNPATH -e RPATH|sed -e 's#.*RPATH=##g' -e 's#.*RUNPATH=##g')
-    [ -z "$RPATH" ] && continue
-    NEWRPATH=
-    for RDIR in $(print '%s\n' $RPATH|cut -d: --output-delimiter=" " -f1-); do
-	    case $RDIR in
+	RPATH=$(chrpath -l "$path" 2>/dev/null| grep -e RUNPATH -e RPATH|sed -e 's#.*RPATH=##g' -e 's#.*RUNPATH=##g')
+	[ -z "$RPATH" ] && continue
+	NEWRPATH=
+	for RDIR in $(print '%s\n' $RPATH|cut -d: --output-delimiter=" " -f1-); do
+		case $RDIR in
 		/lib|/lib32|/libx32|/lib64) 			print '%s\n' removing $RDIR from rpath;;
 		/usr/lib|/usr/lib32|/usr/libx32|/usr/lib64)	print '%s\n' removing $RDIR from rpath;;
 		# often RPM %buildroot is in RPATH, delete it
@@ -39,22 +39,22 @@ while read path; do
 		# often for a directory /.libs/ inside %buildroot
 		*/.libs/*|*/.libs)				print '%s\n' removing $RDIR from rpath;;
 		*)
-		    if [ -z "$NEWRPATH" ]; then
+			if [ -z "$NEWRPATH" ]; then
 			NEWRPATH="$RDIR"
-		    else
+			else
 			NEWRPATH="$NEWRPATH:$RDIR"
-		    fi
+			fi
 		;;
-	    esac
-    done
+		esac
+	done
 
-    if [ "$NEWRPATH" = "$RPATH" ]; then
-	    continue
-    elif [ -z "$NEWRPATH" ]; then
-	chrpath -d "$path"
-	printf '%s\n' "Removing rpath ($RPATH) from $path"
-    else
-	chrpath -r "$NEWRPATH" "$path"
-	printf '%s\n' "Removed parts of rpath ($RPATH) from $path, new rpath is $NEWRPATH"
-    fi
+	if [ "$NEWRPATH" = "$RPATH" ]; then
+		continue
+	elif [ -z "$NEWRPATH" ]; then
+		chrpath -d "$path"
+		printf '%s\n' "Removing rpath ($RPATH) from $path"
+	else
+		chrpath -r "$NEWRPATH" "$path"
+		printf '%s\n' "Removed parts of rpath ($RPATH) from $path, new rpath is $NEWRPATH"
+	fi
 done
