adapt for new era

diff --git a/check_elf_files b/check_elf_files
--- a/check_elf_files
+++ b/check_elf_files
@@ -2,16 +2,16 @@
 # Check elf files
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
-LIB="`rpm --eval %{_lib}`"
+LIB="$(rpm --eval %{_lib})"
 export LD_LIBRARY_PATH="$RPM_BUILD_ROOT/$LIB:$RPM_BUILD_ROOT/usr/$LIB"
 
 
@@ -23,13 +23,13 @@ find "$RPM_BUILD_ROOT" -type f \( -executable -o -name \*.so\* \) -a \
 xargs  --no-run-if-empty -0 file -N -L |
 grep -e '\.so.*: ELF.*shared' -e ': ELF.*executable' |
 while read match; do
-path="`echo $match | sed -e 's#\(\.so.*\): ELF.*shared.*#\1#' -e 's#: ELF.*executable.*##'`"
-syspath="`echo $path | sed -e \"s#^$RPM_BUILD_ROOT##\"`"
-if echo $match | grep -q -e ': ELF'; then
-    unused_libs="`ldd -u -r $path 2> /dev/null | grep /`"
+path="$(printf '%s\n' $match | sed -e 's#\(\.so.*\): ELF.*shared.*#\1#' -e 's#: ELF.*executable.*##')"
+syspath="$(printf '%s\n' $path | sed -e \"s#^$RPM_BUILD_ROOT##\")"
+if printf '%s\n' $match | grep -q -e ': ELF'; then
+    unused_libs="$(ldd -u -r $path 2> /dev/null | grep /)"
     if [ -n "$unused_libs" ]; then
-    	echo "Warning: unused libraries in $syspath: " >&2
-	echo "$unused_libs" >&2
+	printf '%s\n' "Warning: unused libraries in $syspath: " >&2
+	printf '%s\n' "$unused_libs" >&2
     fi
 fi
 done
@@ -41,11 +41,11 @@ find "$RPM_BUILD_ROOT" -type f -name \*.so\*  -a \
 xargs  --no-run-if-empty -0 file -N -L |
 grep -e '\.so.*: ELF.*shared' |
 while read match; do
-path="`echo $match | sed -e 's#\(\.so.*\): ELF.*shared.*#\1#'`"
-syspath="`echo $path | sed -e \"s#^$RPM_BUILD_ROOT##\"`"
-unused_libs="`ldd -u -r $path 2> /dev/null | grep /`"
-undefined_symbols="`ldd -r $path 2>&1 | grep '^undefined symbol: '| sed -e 's#^undefined symbol:##g' -e \"s#($path).*##g\" | tr -d '\n' | tr -d '\t'`"
+path="$(printf '%s\n' $match | sed -e 's#\(\.so.*\): ELF.*shared.*#\1#')"
+syspath="$(printf '%s\n' $path | sed -e \"s#^$RPM_BUILD_ROOT##\")"
+unused_libs="$(ldd -u -r $path 2> /dev/null | grep /)"
+undefined_symbols="$(ldd -r $path 2>&1 | grep '^undefined symbol: '| sed -e 's#^undefined symbol:##g' -e \"s#($path).*##g\" | tr -d '\n' | tr -d '\t')"
 if [ -n "$undefined_symbols" ]; then
-    echo "Warning: undefined symbols in $syspath:$undefined_symbols" >&2
+    printf '%s\n' "Warning: undefined symbols in $syspath:$undefined_symbols" >&2
 fi
 done
diff --git a/clean_perl b/clean_perl
--- a/clean_perl
+++ b/clean_perl
@@ -1,20 +1,20 @@
 #!/bin/sh
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
 perldirs="$RPM_BUILD_ROOT/usr/lib/perl5 $RPM_BUILD_ROOT/usr/lib64/perl5 $RPM_BUILD_ROOT/usr/share/perl5"
 d=""
 for i in $perldirs; do
-	[ -d "$i" ] || continue
-	d="$d $i"
+    [ -d "$i" ] || continue
+    d="$d $i"
 done
 [ -z "$d" ] && exit 0
 
@@ -22,7 +22,7 @@ find $d -name ".packlist" -o -name perllocal.pod | xargs rm -f
 
 for i in $(find $d -name "*.bs"); do
     if [ -s $i ]; then
-	echo "non empty .bs file!"
+	printf '%s\n' "non empty .bs file!"
     else
 	rm -f $i
     fi
diff --git a/fix_eol b/fix_eol
--- a/fix_eol
+++ b/fix_eol
@@ -2,17 +2,17 @@
 # convert end of line patterns from DOS to UNIX
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
 if [ -n "$1" ]; then
-    DIRECTORY=$(echo $1 | sed -e "s#^$RPM_BUILD_ROOT##g")
+    DIRECTORY=$(printf '%s\n' $1 | sed -e "s#^$RPM_BUILD_ROOT##g")
     if [ ! -d "$RPM_BUILD_ROOT$DIRECTORY" ]; then
 	exit 0
     fi
diff --git a/fix_file_permissions b/fix_file_permissions
--- a/fix_file_permissions
+++ b/fix_file_permissions
@@ -1,12 +1,12 @@
 #!/bin/sh
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
@@ -28,11 +28,11 @@ done
 if [ -d "${RPM_BUILD_ROOT}/usr/share/info/" ]; then
     find "${RPM_BUILD_ROOT}/usr/share/info/" \
 	-type f -print0 |
-    xargs  --no-run-if-empty -0 chmod 644
+    xargs --no-run-if-empty -0 chmod 644
 fi
 
 if [ -d "${RPM_BUILD_ROOT}/usr/share/man/" ]; then
     find "${RPM_BUILD_ROOT}/usr/share/man/" \
 	-type f -print0 |
-    xargs  --no-run-if-empty -0 chmod 644
+    xargs --no-run-if-empty -0 chmod 644
 fi
diff --git a/fix_mo b/fix_mo
--- a/fix_mo
+++ b/fix_mo
@@ -10,12 +10,12 @@
 #---------------------------------------------------------------
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
@@ -40,7 +40,7 @@ for i in "$KO_MESSAGES"/*.mo ; do
 	sed 's:그놈:GNOME:g' < $TMP > $TMP2 && msgfmt -o $i $TMP2
 	ret=$?
     else
-	echo "Unsupported encoding" 1>&2
+	printf '%s\n' "Unsupported encoding" 1>&2
     fi
 done
 
diff --git a/fix_pamd b/fix_pamd
--- a/fix_pamd
+++ b/fix_pamd
@@ -1,18 +1,18 @@
 #!/bin/sh
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
-configs=`find $RPM_BUILD_ROOT/etc/pam.d/ -type f ! -type l 2> /dev/null`
+configs=$(find $RPM_BUILD_ROOT/etc/pam.d/ -type f ! -type l 2> /dev/null)
 if [ -n "$configs" ]; then
-    echo -n "Fixing pam.d config files..."
+    printf '%s\n' "Fixing pam.d config files..."
     sed -e 's,/lib64/security/,,g ; s,/lib/security/,,g' $configs
-    echo "done"
+    printf '%s\n' "...done"
 fi
diff --git a/fix_pkgconfig b/fix_pkgconfig
--- a/fix_pkgconfig
+++ b/fix_pkgconfig
@@ -7,23 +7,23 @@
 # (c) Andrey Bondrov <andrey.bondrov@rosalab.ru> 2016
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
-for pc in $(find "$RPM_BUILD_ROOT" -name \*.pc); do
+for pc in $(find "$RPM_BUILD_ROOT" -name \*.pc -type f); do
 	export PKG_CONFIG_PATH="$(dirname $pc)"
 	pcfile="$(basename $pc)"
-	pcmodule="$(echo $pcfile|cut -d. -f1)"
+	pcmodule="$(printf '%s\n' $pcfile|cut -d. -f1)"
 	for variable in $(pkg-config --print-variables "$pcmodule"); do
 		dir=$(pkg-config --variable="$variable" "$pcmodule")
 		if [[ "$dir" == "/"* && -d "$dir" ]]; then
-			if [ "$dir" != "`realpath $dir`" ]; then
+			if [ "$dir" != "$(realpath $dir)" ]; then
 				parentdir=$(dirname ${dir})
 				subdir=$(basename ${dir})
 				regexp="-e s|\(${variable}=.*/${subdir}\)/.*\$|\1|g" 
diff --git a/fix_xdg b/fix_xdg
--- a/fix_xdg
+++ b/fix_xdg
@@ -2,12 +2,12 @@
 # Fix .desktop files to be compliant with XDG specification
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
@@ -18,4 +18,3 @@ do
     # if these lines do not end with '='
     sed -i 's/^\(Actions=.*\|MimeType=.*\|OnlyShowIn=.*\|Categories=.*\)\([[:alnum:]]\)[[:space:]]*$/\1\2;/' "$f"
 done
-
diff --git a/lib_symlinks b/lib_symlinks
--- a/lib_symlinks
+++ b/lib_symlinks
@@ -5,7 +5,7 @@
 # File            : lib_symlinks
 # Author          : Frederic Lepied
 # Created On      : Tue Nov  7 08:33:05 2000
-# Description	  : Run ldconfig to create symlinks to libraries.
+# Description     : Run ldconfig to create symlinks to libraries.
 #
 # Copyright (C) 2000 by Frederic Lepied <flepied@mandrakesoft.com>
 # Redistribution of this file is permitted under the terms of the GNU 
@@ -13,21 +13,20 @@
 #---------------------------------------------------------------
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
-libs=`find "$RPM_BUILD_ROOT" -type d \
+libs=$(find "$RPM_BUILD_ROOT" -type d \
    -a "(" -name lib -o -name lib64 ")" \
-   -a ! "(" -path '*/usr/src/debug*' -o -path '*/usr/lib/debug*' ")" \
-   `
+   -a ! "(" -path '*/usr/src/debug*' -o -path '*/usr/lib/debug*' ")")
 
-if [ -n "$libs" -o -n "$EXTRA_LIBS_TO_SYMLINK" ]; then
+if [ -n "$libs" ] || [ -n "$EXTRA_LIBS_TO_SYMLINK" ]; then
     /sbin/ldconfig -n -N $libs $EXTRA_LIBS_TO_SYMLINK
 fi
 
diff --git a/python_shebangs b/python_shebangs
--- a/python_shebangs
+++ b/python_shebangs
@@ -1,12 +1,12 @@
 #!/bin/sh
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
@@ -15,7 +15,7 @@ set -efu
 # otherwise we will have to switch to bashisms and require /dev/fd/*
 tmpfile="$(mktemp)"
 trap 'rm -f "$tmpfile"' EXIT
-echo 0 > "$tmpfile"
+printf '%s\n' "0" > "$tmpfile"
 
 for dir in /bin /usr/bin /sbin /usr/sbin /usr/libexec
 do
@@ -32,9 +32,9 @@ do
     # #! /usr/bin/env python
     # Note that a space may be in the end of the shebang line
 	if head -n 1 "$file" | grep -qE '^#!([[:blank:]])*.*(/python|[[:blank:]]python)([[:blank:]])*$' ; then
-	    echo "Unversioned Python shebangs are not allowed. Specify python3 or python2 explicitly in $file"
+	    printf '%s\n' "Unversioned Python shebangs are not allowed. Specify python3 or python2 explicitly in $file"
 	    # Do not fail on the 1st error, print all errors at one time
-	    echo 1 > "$tmpfile"
+	    printf '%s\n' "1" > "$tmpfile"
 	fi
     done
 done
diff --git a/remove_info_dir b/remove_info_dir
--- a/remove_info_dir
+++ b/remove_info_dir
@@ -1,20 +1,19 @@
 #!/bin/sh
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
-INFODIR=`rpm --eval %{_infodir}/dir`
+INFODIR=$(rpm --eval %{_infodir}/dir)
 
 dir="$RPM_BUILD_ROOT/$INFODIR"
 
-if [ -f $dir -a ! -f "$RPM_BUILD_ROOT/sbin/install-info" -a ! -f "$RPM_BUILD_ROOT/usr/sbin/install-info" ]; then
-    rm -f $dir 
+if [ -f $dir ] && [ ! -f "$RPM_BUILD_ROOT/sbin/install-info" ] && [ ! -f "$RPM_BUILD_ROOT/usr/sbin/install-info" ]; then
+    rm -f $dir
 fi
-
diff --git a/remove_libtool_files b/remove_libtool_files
--- a/remove_libtool_files
+++ b/remove_libtool_files
@@ -1,12 +1,12 @@
 #!/bin/sh
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
diff --git a/remove_rpath b/remove_rpath
--- a/remove_rpath
+++ b/remove_rpath
@@ -1,12 +1,12 @@
 #!/bin/sh
 
 if [ -z "$RPM_BUILD_ROOT" ]; then
-    echo "No build root defined" >&2
+    printf '%s\n' "No build root defined" >&2
     exit 1
 fi
 
 if [ ! -d "$RPM_BUILD_ROOT" ]; then
-    echo "Invalid build root" >&2
+    printf '%s\n' "Invalid build root" >&2
     exit 1
 fi
 
@@ -14,6 +14,14 @@ find "$RPM_BUILD_ROOT" \
     ! -path "${RPM_BUILD_ROOT}/usr/lib/debug/*" \
     ! -path "${RPM_BUILD_ROOT}/usr/doc/*" \
     ! -path "${RPM_BUILD_ROOT}/usr/share/doc/*" \
+    ! -path "${RPM_BUILD_ROOT}/usr/share/man/*" \
+    ! -path "${RPM_BUILD_ROOT}/usr/share/mime/*" \
+    ! -path "${RPM_BUILD_ROOT}/usr/share/icons/*" \
+    ! -path "${RPM_BUILD_ROOT}/usr/share/pixmaps/*" \
+    ! -path "${RPM_BUILD_ROOT}/usr/share/zoneinfo/*" \
+    ! -path "${RPM_BUILD_ROOT}/usr/share/locale/*" \
+    ! -path "${RPM_BUILD_ROOT}/usr/src/*" \
+    ! -path "${RPM_BUILD_ROOT}/usr/include/*" \
     -type f  -print0 |
 xargs  --no-run-if-empty -0 file -N -F ' //magic:' |
 grep -e "ELF" |
@@ -22,14 +30,14 @@ while read path; do
     RPATH=$(chrpath -l "$path" 2>/dev/null| grep -e RUNPATH -e RPATH|sed -e 's#.*RPATH=##g' -e 's#.*RUNPATH=##g')
     [ -z "$RPATH" ] && continue
     NEWRPATH=
-    for RDIR in $(echo $RPATH|cut -d: --output-delimiter=" " -f1-); do
+    for RDIR in $(print '%s\n' $RPATH|cut -d: --output-delimiter=" " -f1-); do
 	    case $RDIR in
-		/lib|/lib32|/libx32|/lib64) 			echo removing $RDIR from rpath;;
-		/usr/lib|/usr/lib32|/usr/libx32|/usr/lib64)	echo removing $RDIR from rpath;;
+		/lib|/lib32|/libx32|/lib64) 			print '%s\n' removing $RDIR from rpath;;
+		/usr/lib|/usr/lib32|/usr/libx32|/usr/lib64)	print '%s\n' removing $RDIR from rpath;;
 		# often RPM %buildroot is in RPATH, delete it
-		*/BUILD/*)					echo removing $RDIR from rpath;;
+		*/BUILD/*)					print '%s\n' removing $RDIR from rpath;;
 		# often for a directory /.libs/ inside %buildroot
-		*/.libs/*|*/.libs)				echo removing $RDIR from rpath;;
+		*/.libs/*|*/.libs)				print '%s\n' removing $RDIR from rpath;;
 		*)
 		    if [ -z "$NEWRPATH" ]; then
 			NEWRPATH="$RDIR"
@@ -43,10 +51,10 @@ while read path; do
     if [ "$NEWRPATH" = "$RPATH" ]; then
 	    continue
     elif [ -z "$NEWRPATH" ]; then
-        chrpath -d "$path"
-        echo "Removing rpath ($RPATH) from $path"
+	chrpath -d "$path"
+	printf '%s\n' "Removing rpath ($RPATH) from $path"
     else
-        chrpath -r "$NEWRPATH" "$path"
-        echo "Removed parts of rpath ($RPATH) from $path, new rpath is $NEWRPATH"
+	chrpath -r "$NEWRPATH" "$path"
+	printf '%s\n' "Removed parts of rpath ($RPATH) from $path, new rpath is $NEWRPATH"
     fi
 done
